name: model-training
on: [workflow_dispatch]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: python:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          run-as root pip install -r requirements.txt
          pip freeze
          python train.py
          cat metrics.txt > report.md
          cml-publish confusion_matrix.png --md >> report.md
          cml-send-comment report.md
